[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = ".netlify/functions"

[[redirects]]
  from = "http://*"
  to = "https://hitlift.app/:splat"
  status = 301
  force = true
