[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = ".netlify/functions"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "http://realstarter.example.app/*"
  to = "https://realstarter.example.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.realstarter.example.app/*"
  to = "https://realstarter.example.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.realstarter.example.app/*"
  to = "https://realstarter.example.app/:splat"
  status = 301
  force = true
